<#
.SYNOPSIS
    Compile PromptCAD.exe, the rebranded launcher shim.

.DESCRIPTION
    Uses the C# compiler that ships with the .NET Framework, present on every
    supported Windows install, so building the launcher needs no SDK, no
    toolchain download and no elevation.

    Requires branding\generated\PromptCAD.ico, so run branding\build_icons.py
    first. installer\build.ps1 does both in order.
#>
[CmdletBinding()]
param(
    [string] $OutputDir,
    [string] $Version
)

$ErrorActionPreference = 'Stop'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$repo = Split-Path -Parent $here
if (-not $OutputDir) { $OutputDir = Join-Path $here 'generated' }
if (-not $Version) {
    $Version = (Get-Content (Join-Path $repo 'VERSION') -Raw).Trim()
}

# .NET wants a four-part version; VERSION carries the usual three.
$assemblyVersion = $Version
while (($assemblyVersion -split '\.').Count -lt 4) { $assemblyVersion += '.0' }

$source = Join-Path $here 'PromptCAD.cs'
$icon = Join-Path $repo 'branding\generated\PromptCAD.ico'
$output = Join-Path $OutputDir 'PromptCAD.exe'

if (-not (Test-Path $icon)) {
    throw "Icon not found: $icon`nRun branding\build_icons.py first."
}
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

# Newest framework first; v4.0.30319 is the one that has shipped in-box since
# Windows 8, so this resolves on any machine that can run the installer.
$csc = Get-ChildItem 'C:\Windows\Microsoft.NET\Framework64\v*\csc.exe' -ErrorAction SilentlyContinue |
    Sort-Object FullName -Descending |
    Select-Object -First 1 -ExpandProperty FullName

if (-not $csc) {
    throw 'No C# compiler found under C:\Windows\Microsoft.NET\Framework64.'
}

Write-Host "Compiling PromptCAD.exe with $csc (version $Version)"

# Generated rather than hand-edited so the exe, the installer and Add/Remove
# Programs all read their version from the same VERSION file.
$assemblyInfo = Join-Path $OutputDir 'AssemblyInfo.g.cs'
@"
// Generated by build_launcher.ps1 - do not edit.
using System.Reflection;

[assembly: AssemblyVersion("$assemblyVersion")]
[assembly: AssemblyFileVersion("$assemblyVersion")]
[assembly: AssemblyInformationalVersion("$Version")]
"@ | Set-Content -Path $assemblyInfo -Encoding utf8

& $csc /nologo /target:winexe /optimize+ /platform:anycpu `
    "/win32icon:$icon" `
    /reference:System.Windows.Forms.dll `
    "/out:$output" `
    "$source" "$assemblyInfo"

if ($LASTEXITCODE -ne 0) { throw "csc.exe failed with exit code $LASTEXITCODE" }

$size = (Get-Item $output).Length
Write-Host "  $output ($('{0:N0}' -f $size) bytes)"
